### PR TITLE
Cleaning up command line options. Added in ripeBlock

### PR DESCRIPTION
**Pull request by tjayrush**
ripeBlock tells blaze which blocks to write to the 'ripe' folder. Ripe blocks can be consolidated. If a block is prior to 'ripeBlock' it gets written to 'unripe' folder. 'Unripe' blocks will be re-visited. 'Ripe' blocks will not. Also removed unused commands seed, query, status, leech. Add commands back with 'cobra' (https://github.com/spf13/cobra).

### CODE REVIEW

**Review by naterush — APPROVED** [review]
Looks good.

**Review by naterush — CHANGES_REQUESTED** [review]
Actually: can we change ripeBlock -> finalizedBlock? No need for more lingo than we already have. Otherwise, looks good.

**Comment by tjayrush** [comment]
Can you think of a better word than 'finalized'? The reason I'm asking is because that word is already used throughout TrueBlocks to mean 'finished processing, incorporated in the sorted, binary index, never revisiting.'  Ripe means to me 'ready to be picked.' That is, old enough that we won't re-scrape from the chain, but not yet 'consolidated' into the binary index. Can you think of a better word than 'ripe' but not 'finalized'? I agree we want to avoid lingo, but I don't want to use that word.

**Comment by tjayrush** [comment]
Can you merge this?

-------------------------------
Thomas Jay Rush
TrueBlocks.io
jrush@trueblocks.io
(610) 937-2593

**Pull request merged**
